Twitch OAuth2
SevenTV/REST pull request #3
Opened 2021-10-13 14:02 UTC by AnatoleAM

2021-10-15 20:38 UTC, TroyDota requested changes
Remove it WeirdChamp

2021-10-15 20:38 UTC, TroyDota commented on src/externalapis/externalapis.go
> +	fmt.Println(string(b))
Tssk

2021-10-15 20:43 UTC, TroyDota requested changes

2021-10-15 20:43 UTC, TroyDota commented on src/configure/collections.go
> +			Keys: bson.M{"username": 1},
you will have to manually change this index.

2021-10-15 20:43 UTC, TroyDota commented on src/server/v3/authentication/twitch.oauth2.go
> +		token, _, err := auth.VerifyJWT(gCtx.Config().Credentials.JWTSecret, csrfToken)
does this work?

2021-10-15 20:43 UTC, TroyDota commented on src/server/v3/authentication/twitch.oauth2.go
> +		if err = externalapis.ReadRequestResponse(resp, &grant); err != nil {
This shouldnt work.

2021-10-15 20:43 UTC, TroyDota commented on src/server/v3/authentication/twitch.oauth2.go
> +			if err = doc.Decode(&user); err == mongo.ErrNoDocuments {
Neither should this.

2021-10-16 01:38 UTC, AnatoleAM commented on src/configure/collections.go
> +			Keys: bson.M{"username": 1},
That's fine this isn't deployed anywhere, I already did so locally

2021-10-16 01:38 UTC, AnatoleAM commented on src/server/v3/authentication/twitch.oauth2.go
> +		if err = externalapis.ReadRequestResponse(resp, &grant); err != nil {
I believe so, what would be wrong with it?

2021-10-16 01:39 UTC, AnatoleAM commented on src/server/v3/authentication/twitch.oauth2.go
> +			if err = doc.Decode(&user); err == mongo.ErrNoDocuments {
What's wrong with that?

2021-10-16 01:49 UTC, TroyDota commented on src/server/v3/authentication/twitch.oauth2.go
> +		if err = externalapis.ReadRequestResponse(resp, &grant); err != nil {
remove the * from the `var grant *OAuth2AuthorizedResponse`

2021-10-16 01:50 UTC, TroyDota commented on src/server/v3/authentication/twitch.oauth2.go
> +			if err = doc.Decode(&user); err == mongo.ErrNoDocuments {
The same as above, you are taking the pointer of a pointer where the pointer is null. This is wrong, you should do 

user := &User{}
and then unmarshal without passing the pointer 
ie. `.Decode(user)`

2021-10-16 01:51 UTC, TroyDota commented on src/server/v3/authentication/twitch.oauth2.go
> +		if err = externalapis.ReadRequestResponse(resp, &grant); err != nil {
or define the grant liek this

```go
grant := &OAuth2AuthorizedResponse{}
if err = externalapis.ReadRequestResponse(resp, grant); err != nil {
```

2021-10-16 01:51 UTC, TroyDota commented on src/server/v3/authentication/twitch.oauth2.go
> +		token, _, err := auth.VerifyJWT(gCtx.Config().Credentials.JWTSecret, csrfToken)
Same as below.

2021-10-16 01:51 UTC, TroyDota commented on src/externalapis/externalapis.go
> +	fmt.Println(string(b))
remove fmt.Println

2021-10-17 04:15 UTC, merged